//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.Negocio.Base" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException))]
    public partial class ExceptionBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
        "Exceptions")]
    [System.SerializableAttribute()]
    public partial class AccesoDatosException : SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.ExceptionBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoFotoInmueble", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.Negocio.Gest" +
        "ion.AltasDocumentos.Enum")]
    public enum TipoFotoInmueble : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        I = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orientacion", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.Negocio.Gest" +
        "ion.AltasDocumentos.Enum")]
    public enum Orientacion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        N = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        S = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        O = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDocumental.IAltasDocumentos")]
    public interface IAltasDocumentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertResolucionJudicial", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertResolucionJudicialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertResolucionJudicialAccesoDatosExceptionF" +
            "ault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertResolucionJudicial(string descripcion, System.DateTime fecha, string autoridadJudicial, string numeroResolucion, System.Nullable<decimal> idOficialia, string numFolio, string lugar, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateResolucionJudicial", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateResolucionJudicialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateResolucionJudicialAccesoDatosExceptionF" +
            "ault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateResolucionJudicial(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, int idOficialia, string folio, string lugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertSATI", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertSATIResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertSATIAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertSATI(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateDocumentoGenerico", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateDocumentoGenericoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateDocumentoGenericoAccesoDatosExceptionFa" +
            "ult", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateDocumentoGenerico(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/EstablecerDocumentoDefinitivo", ReplyAction="http://tempuri.org/IAltasDocumentos/EstablecerDocumentoDefinitivoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/EstablecerDocumentoDefinitivoAccesoDatosExcep" +
            "tionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void EstablecerDocumentoDefinitivo(decimal idDocumentoDigital);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertAvaluoCatastral", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertAvaluoCatastralResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertAvaluoCatastralAccesoDatosExceptionFaul" +
            "t", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertAvaluoCatastral(byte[] fichero, string nombreFichero, string descripcion, System.DateTime fecha, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertAvaluoComercial", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertAvaluoComercialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertAvaluoComercialAccesoDatosExceptionFaul" +
            "t", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertAvaluoComercial(byte[] fichero, string nombreFichero, string descripcion, System.DateTime fecha, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertCartaPoder", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertCartaPoderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertCartaPoderAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertCartaPoder(string lugar, string descripcion, System.DateTime fecha, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateCartaPoder", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateCartaPoderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateCartaPoderAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateCartaPoder(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string lugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertDocumentoAdministrativo", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertDocumentoAdministrativoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertDocumentoAdministrativoAccesoDatosExcep" +
            "tionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertDocumentoAdministrativo(string descripcion, int idOficialia, string numeroResolucion, System.DateTime fecha, string organismo, string folio, string lugar, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateDocumentoAdministrativo", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateDocumentoAdministrativoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateDocumentoAdministrativoAccesoDatosExcep" +
            "tionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateDocumentoAdministrativo(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, int idOficialia, string folio, string lugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertLicenciaObras", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertLicenciaObrasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertLicenciaObrasAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertLicenciaObras(string descripcion, decimal idDelegacion, decimal numeroLicencia, string numeroFolio, System.DateTime fechaInicioVigencia, System.DateTime fechaFinVigencia, System.DateTime fecha, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateTerminacionLicencia", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateTerminacionLicenciaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateTerminacionLicenciaAccesoDatosException" +
            "Fault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateTerminacionLicencia(decimal idDocumentoDigital, System.DateTime fechaTerminacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateLicenciaObras", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateLicenciaObrasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateLicenciaObrasAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateLicenciaObras(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string numeroFolio, System.DateTime fechaInicioVigencia, System.DateTime fechaFinVigencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertDocumentoPrivado", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertDocumentoPrivadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertDocumentoPrivadoAccesoDatosExceptionFau" +
            "lt", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertDocumentoPrivado(string lugar, string descripcion, System.DateTime fecha, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateDocumentoPrivado", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateDocumentoPrivadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateDocumentoPrivadoAccesoDatosExceptionFau" +
            "lt", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateDocumentoPrivado(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string lugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertEscrituraPublica", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertEscrituraPublicaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertEscrituraPublicaAccesoDatosExceptionFau" +
            "lt", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertEscrituraPublica(string descripcion, decimal idNotario, System.Nullable<decimal> numeroProtocolo, System.DateTime fecha, string lugar, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateEscrituraPublica", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateEscrituraPublicaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateEscrituraPublicaAccesoDatosExceptionFau" +
            "lt", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateEscrituraPublica(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string lugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertF4", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertF4Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertF4AccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertF4(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertFotoInmueble", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertFotoInmuebleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertFotoInmuebleAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertFotoInmueble(byte[] fichero, string nombreFichero, string descripcion, System.DateTime fecha, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.TipoFotoInmueble tipoFotoInm, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateFotoInmueble", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateFotoInmuebleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateFotoInmuebleAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateFotoInmueble(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.TipoFotoInmueble tipoFotoInm, byte[] fichero, string nombreFichero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertFotoManzana", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertFotoManzanaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertFotoManzanaAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertFotoManzana(byte[] fichero, string nombreFichero, string descripcion, System.DateTime fecha, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.Orientacion orientacion, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateFotoManzana", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateFotoManzanaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateFotoManzanaAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateFotoManzana(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.Orientacion orientacion, byte[] fichero, string nombreFichero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertMemoriaDescriptiva", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertMemoriaDescriptivaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertMemoriaDescriptivaAccesoDatosExceptionF" +
            "ault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertMemoriaDescriptiva(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertOficio", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertOficioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertOficioAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertOficio(byte[] fichero, string nombreFichero, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertDocumentoOficio", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertDocumentoOficioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertDocumentoOficioAccesoDatosExceptionFaul" +
            "t", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertDocumentoOficio(string descripcion, int idOficialia, string numeroResolucion, System.DateTime fecha, string organismo, string folio, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdateDocumentoOficio", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdateDocumentoOficioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdateDocumentoOficioAccesoDatosExceptionFaul" +
            "t", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdateDocumentoOficio(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, int idOficialia, string folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertNoAcceso", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertNoAccesoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertNoAccesoAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertNoAcceso(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertComplementario", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertComplementarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertComplementarioAccesoDatosExceptionFault" +
            "", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertComplementario(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertFotoNoAcceso", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertFotoNoAccesoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertFotoNoAccesoAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertFotoNoAcceso(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertOtros", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertOtrosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertOtrosAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertOtros(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertPlanoArquitectonico", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertPlanoArquitectonicoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertPlanoArquitectonicoAccesoDatosException" +
            "Fault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertPlanoArquitectonico(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertPlanosCampo", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertPlanosCampoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertPlanosCampoAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertPlanosCampo(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertPoderNotarial", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertPoderNotarialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertPoderNotarialAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertPoderNotarial(string descripcion, decimal idNotario, decimal numeroProtocolo, System.DateTime fecha, string lugar, System.Nullable<decimal> idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/UpdatePoderNotarial", ReplyAction="http://tempuri.org/IAltasDocumentos/UpdatePoderNotarialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/UpdatePoderNotarialAccesoDatosExceptionFault", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        void UpdatePoderNotarial(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string lugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertProrrogaLicencia", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertProrrogaLicenciaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertProrrogaLicenciaAccesoDatosExceptionFau" +
            "lt", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertProrrogaLicencia(decimal idDocumentoDigital, decimal numeroProrroga, System.DateTime fechaInicio, System.DateTime fechaVencimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAltasDocumentos/InsertRegistroPropiedad", ReplyAction="http://tempuri.org/IAltasDocumentos/InsertRegistroPropiedadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.AccesoDatosException), Action="http://tempuri.org/IAltasDocumentos/InsertRegistroPropiedadAccesoDatosExceptionFa" +
            "ult", Name="AccesoDatosException", Namespace="http://schemas.datacontract.org/2004/07/SIGAPred.Documental.Services.AccesoDatos." +
            "Exceptions")]
        System.Nullable<decimal> InsertRegistroPropiedad(decimal idDocumentoDigital, string esAntecedente, System.DateTime fechaInscripcion, System.Nullable<decimal> folioReal, string seccion, string volumen, System.Nullable<decimal> tomo, System.Nullable<decimal> foja, System.Nullable<decimal> partida, string confrontado, System.DateTime fechaConfronta, string libro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAltasDocumentosChannel : SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.IAltasDocumentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AltasDocumentosClient : System.ServiceModel.ClientBase<SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.IAltasDocumentos>, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.IAltasDocumentos {
        
        public AltasDocumentosClient() {
        }
        
        public AltasDocumentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AltasDocumentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AltasDocumentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AltasDocumentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<decimal> InsertResolucionJudicial(string descripcion, System.DateTime fecha, string autoridadJudicial, string numeroResolucion, System.Nullable<decimal> idOficialia, string numFolio, string lugar, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertResolucionJudicial(descripcion, fecha, autoridadJudicial, numeroResolucion, idOficialia, numFolio, lugar, idUsuario);
        }
        
        public void UpdateResolucionJudicial(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, int idOficialia, string folio, string lugar) {
            base.Channel.UpdateResolucionJudicial(idDocumentoDigital, descripcion, fecha, idOficialia, folio, lugar);
        }
        
        public System.Nullable<decimal> InsertSATI(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertSATI(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public void UpdateDocumentoGenerico(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero) {
            base.Channel.UpdateDocumentoGenerico(idDocumentoDigital, descripcion, fecha, fichero, nombreFichero);
        }
        
        public void EstablecerDocumentoDefinitivo(decimal idDocumentoDigital) {
            base.Channel.EstablecerDocumentoDefinitivo(idDocumentoDigital);
        }
        
        public System.Nullable<decimal> InsertAvaluoCatastral(byte[] fichero, string nombreFichero, string descripcion, System.DateTime fecha, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertAvaluoCatastral(fichero, nombreFichero, descripcion, fecha, idUsuario);
        }
        
        public System.Nullable<decimal> InsertAvaluoComercial(byte[] fichero, string nombreFichero, string descripcion, System.DateTime fecha, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertAvaluoComercial(fichero, nombreFichero, descripcion, fecha, idUsuario);
        }
        
        public System.Nullable<decimal> InsertCartaPoder(string lugar, string descripcion, System.DateTime fecha, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertCartaPoder(lugar, descripcion, fecha, idUsuario);
        }
        
        public void UpdateCartaPoder(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string lugar) {
            base.Channel.UpdateCartaPoder(idDocumentoDigital, descripcion, fecha, lugar);
        }
        
        public System.Nullable<decimal> InsertDocumentoAdministrativo(string descripcion, int idOficialia, string numeroResolucion, System.DateTime fecha, string organismo, string folio, string lugar, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertDocumentoAdministrativo(descripcion, idOficialia, numeroResolucion, fecha, organismo, folio, lugar, idUsuario);
        }
        
        public void UpdateDocumentoAdministrativo(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, int idOficialia, string folio, string lugar) {
            base.Channel.UpdateDocumentoAdministrativo(idDocumentoDigital, descripcion, fecha, idOficialia, folio, lugar);
        }
        
        public System.Nullable<decimal> InsertLicenciaObras(string descripcion, decimal idDelegacion, decimal numeroLicencia, string numeroFolio, System.DateTime fechaInicioVigencia, System.DateTime fechaFinVigencia, System.DateTime fecha, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertLicenciaObras(descripcion, idDelegacion, numeroLicencia, numeroFolio, fechaInicioVigencia, fechaFinVigencia, fecha, idUsuario);
        }
        
        public void UpdateTerminacionLicencia(decimal idDocumentoDigital, System.DateTime fechaTerminacion) {
            base.Channel.UpdateTerminacionLicencia(idDocumentoDigital, fechaTerminacion);
        }
        
        public void UpdateLicenciaObras(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string numeroFolio, System.DateTime fechaInicioVigencia, System.DateTime fechaFinVigencia) {
            base.Channel.UpdateLicenciaObras(idDocumentoDigital, descripcion, fecha, numeroFolio, fechaInicioVigencia, fechaFinVigencia);
        }
        
        public System.Nullable<decimal> InsertDocumentoPrivado(string lugar, string descripcion, System.DateTime fecha, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertDocumentoPrivado(lugar, descripcion, fecha, idUsuario);
        }
        
        public void UpdateDocumentoPrivado(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string lugar) {
            base.Channel.UpdateDocumentoPrivado(idDocumentoDigital, descripcion, fecha, lugar);
        }
        
        public System.Nullable<decimal> InsertEscrituraPublica(string descripcion, decimal idNotario, System.Nullable<decimal> numeroProtocolo, System.DateTime fecha, string lugar, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertEscrituraPublica(descripcion, idNotario, numeroProtocolo, fecha, lugar, idUsuario);
        }
        
        public void UpdateEscrituraPublica(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string lugar) {
            base.Channel.UpdateEscrituraPublica(idDocumentoDigital, descripcion, fecha, lugar);
        }
        
        public System.Nullable<decimal> InsertF4(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertF4(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public System.Nullable<decimal> InsertFotoInmueble(byte[] fichero, string nombreFichero, string descripcion, System.DateTime fecha, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.TipoFotoInmueble tipoFotoInm, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertFotoInmueble(fichero, nombreFichero, descripcion, fecha, tipoFotoInm, idUsuario);
        }
        
        public void UpdateFotoInmueble(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.TipoFotoInmueble tipoFotoInm, byte[] fichero, string nombreFichero) {
            base.Channel.UpdateFotoInmueble(idDocumentoDigital, descripcion, fecha, tipoFotoInm, fichero, nombreFichero);
        }
        
        public System.Nullable<decimal> InsertFotoManzana(byte[] fichero, string nombreFichero, string descripcion, System.DateTime fecha, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.Orientacion orientacion, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertFotoManzana(fichero, nombreFichero, descripcion, fecha, orientacion, idUsuario);
        }
        
        public void UpdateFotoManzana(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, SIGAPred.FuentesExternas.Avaluos.Services.ServiceDocumental.Orientacion orientacion, byte[] fichero, string nombreFichero) {
            base.Channel.UpdateFotoManzana(idDocumentoDigital, descripcion, fecha, orientacion, fichero, nombreFichero);
        }
        
        public System.Nullable<decimal> InsertMemoriaDescriptiva(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertMemoriaDescriptiva(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public System.Nullable<decimal> InsertOficio(byte[] fichero, string nombreFichero, string descripcion) {
            return base.Channel.InsertOficio(fichero, nombreFichero, descripcion);
        }
        
        public System.Nullable<decimal> InsertDocumentoOficio(string descripcion, int idOficialia, string numeroResolucion, System.DateTime fecha, string organismo, string folio, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertDocumentoOficio(descripcion, idOficialia, numeroResolucion, fecha, organismo, folio, idUsuario);
        }
        
        public void UpdateDocumentoOficio(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, int idOficialia, string folio) {
            base.Channel.UpdateDocumentoOficio(idDocumentoDigital, descripcion, fecha, idOficialia, folio);
        }
        
        public System.Nullable<decimal> InsertNoAcceso(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertNoAcceso(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public System.Nullable<decimal> InsertComplementario(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertComplementario(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public System.Nullable<decimal> InsertFotoNoAcceso(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertFotoNoAcceso(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public System.Nullable<decimal> InsertOtros(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertOtros(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public System.Nullable<decimal> InsertPlanoArquitectonico(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertPlanoArquitectonico(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public System.Nullable<decimal> InsertPlanosCampo(string descripcion, System.DateTime fecha, byte[] fichero, string nombreFichero, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertPlanosCampo(descripcion, fecha, fichero, nombreFichero, idUsuario);
        }
        
        public System.Nullable<decimal> InsertPoderNotarial(string descripcion, decimal idNotario, decimal numeroProtocolo, System.DateTime fecha, string lugar, System.Nullable<decimal> idUsuario) {
            return base.Channel.InsertPoderNotarial(descripcion, idNotario, numeroProtocolo, fecha, lugar, idUsuario);
        }
        
        public void UpdatePoderNotarial(decimal idDocumentoDigital, string descripcion, System.DateTime fecha, string lugar) {
            base.Channel.UpdatePoderNotarial(idDocumentoDigital, descripcion, fecha, lugar);
        }
        
        public System.Nullable<decimal> InsertProrrogaLicencia(decimal idDocumentoDigital, decimal numeroProrroga, System.DateTime fechaInicio, System.DateTime fechaVencimiento) {
            return base.Channel.InsertProrrogaLicencia(idDocumentoDigital, numeroProrroga, fechaInicio, fechaVencimiento);
        }
        
        public System.Nullable<decimal> InsertRegistroPropiedad(decimal idDocumentoDigital, string esAntecedente, System.DateTime fechaInscripcion, System.Nullable<decimal> folioReal, string seccion, string volumen, System.Nullable<decimal> tomo, System.Nullable<decimal> foja, System.Nullable<decimal> partida, string confrontado, System.DateTime fechaConfronta, string libro) {
            return base.Channel.InsertRegistroPropiedad(idDocumentoDigital, esAntecedente, fechaInscripcion, folioReal, seccion, volumen, tomo, foja, partida, confrontado, fechaConfronta, libro);
        }
    }
}
